/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.52
 * Generated at: 2023-02-25 14:25:40 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.accountbook;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class assetmanage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1675857165311L));
    _jspx_dependants.put("jar:file:/C:/Study/ProjectMoon/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/ProjectMoon/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\" />\r\n");
      out.write("<script src=\"http://code.jquery.com/jquery-3.5.1.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("$(document).ready(function(){\r\n");
      out.write("	getYear();\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	$('#year').change(function(){\r\n");
      out.write("		var data = $(this).val();\r\n");
      out.write("		var url = '/accountBook/getMonth'\r\n");
      out.write("		console.log(data);\r\n");
      out.write("		$.ajax({\r\n");
      out.write("			type : 'POST',\r\n");
      out.write("			url : url,\r\n");
      out.write("			contentType : 'application/json',\r\n");
      out.write("			data : JSON.stringify({'year' : data}),\r\n");
      out.write("			dataType : 'json',\r\n");
      out.write("			success : function(resultData){\r\n");
      out.write("				var list = '';\r\n");
      out.write("				list += '<option value=\"\" selected>선택';\r\n");
      out.write("				for(var i = 0; i < resultData.length; i++){\r\n");
      out.write("					var item = resultData[i];\r\n");
      out.write("					list += '<option value=\"'+item.month+'\">'+item.month+'';\r\n");
      out.write("				}\r\n");
      out.write("				\r\n");
      out.write("				$('#month').html(list);\r\n");
      out.write("			}\r\n");
      out.write("		})\r\n");
      out.write("		\r\n");
      out.write("	})\r\n");
      out.write("	\r\n");
      out.write("	$('#month').change(function(){\r\n");
      out.write("		var data = 'BANK';\r\n");
      out.write("		var url = '/cdCommon/selectCode'\r\n");
      out.write("		console.log(data);\r\n");
      out.write("		$.ajax({\r\n");
      out.write("			type : 'POST',\r\n");
      out.write("			url : url,\r\n");
      out.write("			contentType : 'application/json',\r\n");
      out.write("			data : JSON.stringify({'code' : data}),\r\n");
      out.write("			dataType : 'json',\r\n");
      out.write("			success : function(resultData){\r\n");
      out.write("				var list = '';\r\n");
      out.write("				console.log(resultData);\r\n");
      out.write("				console.log(resultData.length);\r\n");
      out.write("				list += '<option value=\"\" selected>선택';\r\n");
      out.write("				list += '<option value=\"\">전체';\r\n");
      out.write("				for(var i = 0; i < resultData.length; i++){\r\n");
      out.write("					var item = resultData[i];\r\n");
      out.write("					list += '<option value=\"'+item.mainCategory+'\">'+item.properties+'';\r\n");
      out.write("				}\r\n");
      out.write("				\r\n");
      out.write("				$('#bank').html(list);\r\n");
      out.write("			}\r\n");
      out.write("		})\r\n");
      out.write("	})\r\n");
      out.write("	\r\n");
      out.write("		$('#bank').change(function(){\r\n");
      out.write("		var year = $('#year').val();\r\n");
      out.write("		var month = $('#month').val();\r\n");
      out.write("		var bank = $(this).val();\r\n");
      out.write("		var url = '/accountBook/SelectAccountBookList'\r\n");
      out.write("		$.ajax({\r\n");
      out.write("			type : 'POST',\r\n");
      out.write("			url : url,\r\n");
      out.write("			contentType : 'application/json',\r\n");
      out.write("			data : JSON.stringify({\r\n");
      out.write("					'year' : year,\r\n");
      out.write("					'month' : month,\r\n");
      out.write("					'bank' : bank\r\n");
      out.write("					}),\r\n");
      out.write("			dataType : 'json',\r\n");
      out.write("			success : function(resultData){\r\n");
      out.write("				var revenueList = '';\r\n");
      out.write("				var costList = '';\r\n");
      out.write("				var transferList ='';\r\n");
      out.write("\r\n");
      out.write("				revenueList += '<table>';\r\n");
      out.write("				revenueList += '<tr>';\r\n");
      out.write("				revenueList += '<td>수익</td>';\r\n");
      out.write("				revenueList += '<td></td>';\r\n");
      out.write("				revenueList += '<td></td>';\r\n");
      out.write("				revenueList += '<td></td>';\r\n");
      out.write("				revenueList += '</tr>';\r\n");
      out.write("				\r\n");
      out.write("				costList += '<table>';\r\n");
      out.write("				costList += '<tr>';\r\n");
      out.write("				costList += '<td>비용</td>';\r\n");
      out.write("				costList += '<td></td>';\r\n");
      out.write("				costList += '<td></td>';\r\n");
      out.write("				costList += '<td></td>';\r\n");
      out.write("				costList += '</tr>';\r\n");
      out.write("				\r\n");
      out.write("				\r\n");
      out.write("				for(var i = 0; i < resultData.length; i++){\r\n");
      out.write("					var item = resultData[i];\r\n");
      out.write("					if(item.division == 'ACCOUNT_REVENUE'){\r\n");
      out.write("						revenueList += '<tr>';\r\n");
      out.write("						revenueList += '<td>'+item.date+'</td>';\r\n");
      out.write("						revenueList += '<td>'+item.bank+'</td>';\r\n");
      out.write("						revenueList += '<td>'+item.detail+'</td>';\r\n");
      out.write("						revenueList += '<td>'+item.amount+'</td>';\r\n");
      out.write("						revenueList += '</tr>';\r\n");
      out.write("					} else if(item.division == 'ACCOUNT_COST'){\r\n");
      out.write("						costList += '<tr>';\r\n");
      out.write("						costList += '<td>'+item.date+'</td>';\r\n");
      out.write("						costList += '<td>'+item.bank+'</td>';\r\n");
      out.write("						costList += '<td>'+item.detail+'</td>';\r\n");
      out.write("						costList += '<td>'+item.amount+'</td>';\r\n");
      out.write("						costList += '</tr>';\r\n");
      out.write("					} else{\r\n");
      out.write("					}\r\n");
      out.write("				}\r\n");
      out.write("				revenueList += '</table>';\r\n");
      out.write("				\r\n");
      out.write("				costList += '</table>';\r\n");
      out.write("				\r\n");
      out.write("				transferList += '</table>';\r\n");
      out.write("				\r\n");
      out.write("				\r\n");
      out.write("				$('#nowRevenue').html(revenueList);\r\n");
      out.write("				$('#nowCost').html(costList);\r\n");
      out.write("				\r\n");
      out.write("			}\r\n");
      out.write("		})\r\n");
      out.write("		getBalance(year, month, bank);\r\n");
      out.write("		getSettle(year, month, bank);\r\n");
      out.write("		\r\n");
      out.write("	})\r\n");
      out.write("	\r\n");
      out.write("})\r\n");
      out.write("\r\n");
      out.write("function getBalance(year, month, bank){\r\n");
      out.write("	var url = '/accountBook/getBalance'\r\n");
      out.write("	var year = year;\r\n");
      out.write("	var month = month;\r\n");
      out.write("	var bank = bank;\r\n");
      out.write("	$.ajax({\r\n");
      out.write("		type : 'POST',\r\n");
      out.write("		url : url,\r\n");
      out.write("		contentType : 'application/json',\r\n");
      out.write("		data : JSON.stringify({\r\n");
      out.write("			'year' : year,\r\n");
      out.write("			'month' : month,\r\n");
      out.write("			'bank' : bank\r\n");
      out.write("			}),\r\n");
      out.write("		dataType : 'json',\r\n");
      out.write("		success : function(resultData){\r\n");
      out.write("			console.log(resultData);\r\n");
      out.write("			var bankList = '';\r\n");
      out.write("			bankList += '<table>';\r\n");
      out.write("			bankList += '<tr>';\r\n");
      out.write("			bankList += '<td>은행</td>';\r\n");
      out.write("			bankList += '<td>잔액</td>';\r\n");
      out.write("			bankList += '</tr>';\r\n");
      out.write("			for(var i = 0; i < resultData.length; i++){\r\n");
      out.write("				var item = resultData[i];\r\n");
      out.write("				bankList += '<tr>';\r\n");
      out.write("				bankList += '<td>'+item.bank+'</td>';\r\n");
      out.write("				bankList += '<td>'+item.amount+'</td>';\r\n");
      out.write("				bankList += '</tr>';\r\n");
      out.write("			}\r\n");
      out.write("			bankList += '</table>';\r\n");
      out.write("			$('#prevBank').html(bankList);\r\n");
      out.write("		}\r\n");
      out.write("	})\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function getSettle(year, month, bank){\r\n");
      out.write("	var url = '/accountBook/getSettle';\r\n");
      out.write("	var year = year;\r\n");
      out.write("	var month = month;\r\n");
      out.write("	var bank = bank;\r\n");
      out.write("	$.ajax({\r\n");
      out.write("		type : 'POST',\r\n");
      out.write("		url : url,\r\n");
      out.write("		contentType : 'application/json',\r\n");
      out.write("		data : JSON.stringify({\r\n");
      out.write("			'year' : year,\r\n");
      out.write("			'month' : month,\r\n");
      out.write("			'bank' : bank\r\n");
      out.write("			}),\r\n");
      out.write("		dataType : 'json',\r\n");
      out.write("		success : function(resultData){\r\n");
      out.write("			var bankList = '';\r\n");
      out.write("			bankList += '<table>';\r\n");
      out.write("			bankList += '<tr>';\r\n");
      out.write("			bankList += '<td>은행</td>';\r\n");
      out.write("			bankList += '<td>잔액</td>';\r\n");
      out.write("			bankList += '</tr>';\r\n");
      out.write("			for(var i = 0; i < resultData.length; i++){\r\n");
      out.write("				var item = resultData[i];\r\n");
      out.write("				bankList += '<tr>';\r\n");
      out.write("				bankList += '<td>'+item.bank+'</td>';\r\n");
      out.write("				bankList += '<td>'+item.amount+'</td>';\r\n");
      out.write("				bankList += '</tr>';\r\n");
      out.write("			}\r\n");
      out.write("			bankList += '</table>';\r\n");
      out.write("			$('#settleBank').html(bankList);\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("	})\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function getYear(){\r\n");
      out.write("	var url = '/accountBook/getYear';\r\n");
      out.write("	$.ajax({\r\n");
      out.write("		type : 'POST',\r\n");
      out.write("		url : url,\r\n");
      out.write("		contentType : 'application/json',\r\n");
      out.write("		dataType : 'json',\r\n");
      out.write("		success : function(resultData){\r\n");
      out.write("			var list = '';\r\n");
      out.write("			list += '<option value=\"\" selected>선택';\r\n");
      out.write("			for(var i = 0; i < resultData.length; i++){\r\n");
      out.write("				var item = resultData[i];\r\n");
      out.write("				list += '<option value=\"'+item.year+'\">'+item.year+'';\r\n");
      out.write("			}\r\n");
      out.write("			$('#year').html(list);\r\n");
      out.write("		}\r\n");
      out.write("	})\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function setNewSettle(){\r\n");
      out.write("	var url = '/accountBook/setNewSettle';\r\n");
      out.write("	var year = $('#year').val();\r\n");
      out.write("	var month = $('#month').val();\r\n");
      out.write("	var bank = $('#bank').val();\r\n");
      out.write("	\r\n");
      out.write("	$.ajax({\r\n");
      out.write("		type : 'POST',\r\n");
      out.write("		url : url,\r\n");
      out.write("		contentType : 'application/json',\r\n");
      out.write("		data : JSON.stringify({\r\n");
      out.write("			'year' : year,\r\n");
      out.write("			'month' : month,\r\n");
      out.write("			'bank' : bank\r\n");
      out.write("			}),\r\n");
      out.write("		dataType : 'json',\r\n");
      out.write("		success : function(resultData){\r\n");
      out.write("			var bankList = '';\r\n");
      out.write("			bankList += '<table>';\r\n");
      out.write("			bankList += '<tr>';\r\n");
      out.write("			bankList += '<td>은행</td>';\r\n");
      out.write("			bankList += '<td>잔액</td>';\r\n");
      out.write("			bankList += '</tr>';\r\n");
      out.write("			\r\n");
      out.write("			for(var i = 0; i < resultData.length; i++){\r\n");
      out.write("				var item = resultData[i];\r\n");
      out.write("				bankList += '<tr>';\r\n");
      out.write("				bankList += '<td>'+item.bank+'</td>';\r\n");
      out.write("				bankList += '<td>'+item.amount+'</td>';\r\n");
      out.write("				bankList += '</tr>';\r\n");
      out.write("			}\r\n");
      out.write("			bankList += '</table>';\r\n");
      out.write("			$('#settleBank').html(bankList);\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("	})\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<title>자산 현황</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<div>\r\n");
      out.write("		<form action=\"\" id=\"assetfrm\" name=\"assetfrm\" method=\"POST\">\r\n");
      out.write("			<!-- 기간 선택 -->\r\n");
      out.write("			<div>\r\n");
      out.write("				<!-- 기간 구분 -->\r\n");
      out.write("				<select id=\"year\" name=\"year\">\r\n");
      out.write("				\r\n");
      out.write("				</select>\r\n");
      out.write("\r\n");
      out.write("				<select id=\"month\" name=\"month\">\r\n");
      out.write("					\r\n");
      out.write("				</select>\r\n");
      out.write("				\r\n");
      out.write("				<select id=\"bank\" name=\"bank\">\r\n");
      out.write("					\r\n");
      out.write("				</select>\r\n");
      out.write("				\r\n");
      out.write("			</div>\r\n");
      out.write("			<div id=\"prevBank\">\r\n");
      out.write("				<!-- 전월 잔액 테이블 -->\r\n");
      out.write("			</div>\r\n");
      out.write("			<div id=\"nowRevenue\">\r\n");
      out.write("				<!-- 당월 사용 -->\r\n");
      out.write("				\r\n");
      out.write("			</div>\r\n");
      out.write("			<div id=\"nowCost\">\r\n");
      out.write("			\r\n");
      out.write("			</div>\r\n");
      out.write("			<div id=\"settleBank\">\r\n");
      out.write("				<!-- 당월 잔액 정산 -->\r\n");
      out.write("			</div>\r\n");
      out.write("			<button id=\"settle\" name=\"settle\" onclick=\"setNewSettle();\">새로정산하기</button>\r\n");
      out.write("		</form>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
