/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.52
 * Generated at: 2023-04-02 07:58:43 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.accountbook;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class regist_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1675857165311L));
    _jspx_dependants.put("jar:file:/C:/Study/ProjectMoon/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/ProjectMoon/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\" />\r\n");
      out.write("<script src=\"http://code.jquery.com/jquery-3.5.1.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("$(document).ready(function(){\r\n");
      out.write("\r\n");
      out.write("})\r\n");
      out.write("var num = 0;\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function addrow(){\r\n");
      out.write("	var division = $('#division').val();\r\n");
      out.write("	var divisionDetail = $('#divisionDetail').val();\r\n");
      out.write("	var divisionSubDetail = $('#divisionSubDetail').val()\r\n");
      out.write("	var bank = $('#bank').val();\r\n");
      out.write("	\r\n");
      out.write("	var list = '';\r\n");
      out.write("	list += '<div id=\"accountDiv_'+num+'\">';\r\n");
      out.write("	list += '<br>';\r\n");
      out.write("	list += '<table>';\r\n");
      out.write("	list += '<input type=\"hidden\" id=\"num\" name=\"num\" value=\"'+num+'\">';\r\n");
      out.write("	list += '<select id=\"division_'+num+'\" name=\"division_'+num+'\" onchange=\"divisionChange('+num+', this.value);\"></select>';\r\n");
      out.write("	list += '<select id=\"divisionDetail_'+num+'\" name=\"divisionDetail_'+num+'\" onchange=\"divisionDetailChange('+num+', this.value);\"></select>';\r\n");
      out.write("	list += '<select id=\"divisionSubDetail_'+num+'\" name=\"divisionSubDetail_'+num+'\" onchange=\"divisionSubDetailChange('+num+', this.value);\"></select>';\r\n");
      out.write("	list += '<select id=\"bank_'+num+'\" name=\"bank_'+num+'\"></select>';\r\n");
      out.write("	list += '<td><span>날짜</span></td>';\r\n");
      out.write("	list += '<td><input type=\"date\" id=\"date_'+num+'\" name=\"date_'+num+'\" ></td>';\r\n");
      out.write("	list += '</tr>';\r\n");
      out.write("	list += '<tr>';\r\n");
      out.write("	list += '<td><span>금액</span></td>';\r\n");
      out.write("	list += '<td><input type=\"number\" id=\"amount_'+num+'\" name=\"amount_'+num+'\"></td>';\r\n");
      out.write("	list += '</tr>';\r\n");
      out.write("	list += '<tr>';\r\n");
      out.write("	list += '<td><span>사용처 및 수수료</span></td>';\r\n");
      out.write("	list += '<td><input type=\"text\" id=\"detail_'+num+'\" name=\"detail_'+num+'\" value=\"0\"></td>';\r\n");
      out.write("	list += '</tr>';\r\n");
      out.write("	list += '</table>';\r\n");
      out.write("	list += '<button id=\"deleteAccount_'+num+'\" name=\"deleteAccount_'+num+'\" onclick=\"deleteAccount('+num+')\">거래삭제</button>';\r\n");
      out.write("	list += '</div>';\r\n");
      out.write("	\r\n");
      out.write("	getCode(num);\r\n");
      out.write("	\r\n");
      out.write("	num++;\r\n");
      out.write("	\r\n");
      out.write("	$('#registDetail').append(list);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function getCode(num){\r\n");
      out.write("	console.log(num);\r\n");
      out.write("	var url = '/cdCommon/selectCode';\r\n");
      out.write("	var data = 'AB';\r\n");
      out.write("	$.ajax({\r\n");
      out.write("		type : 'POST',\r\n");
      out.write("		url : url,\r\n");
      out.write("		contentType : 'application/json',\r\n");
      out.write("		data : JSON.stringify({'code' : data}),\r\n");
      out.write("		dataType : 'json',\r\n");
      out.write("		success : function(resultData){\r\n");
      out.write("			var list = '';\r\n");
      out.write("			list += '<option value=\"\" selected>선택';\r\n");
      out.write("			for(var i = 0; i < resultData.length; i++){\r\n");
      out.write("				var item = resultData[i];\r\n");
      out.write("				list += '<option value=\"'+item.mainCategory+'\">'+item.properties+'';\r\n");
      out.write("			}\r\n");
      out.write("			$('#registDetail #division_'+num).html(list);\r\n");
      out.write("		}\r\n");
      out.write("	})\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function divisionChange(num, obj){\r\n");
      out.write("	$('#registDetail #divisionDetail_'+num).val('');\r\n");
      out.write("	$('#registDetail #divisionSubDetail_'+num).val('');\r\n");
      out.write("	$('#registDetail #bank_'+num).val('');\r\n");
      out.write("	var data = obj;\r\n");
      out.write("	var url = '/cdCommon/selectCode'\r\n");
      out.write("	$.ajax({\r\n");
      out.write("		type : 'POST',\r\n");
      out.write("		url : url,\r\n");
      out.write("		contentType : 'application/json',\r\n");
      out.write("		data : JSON.stringify({'code' : data}),\r\n");
      out.write("		dataType : 'json',\r\n");
      out.write("		success : function(resultData){\r\n");
      out.write("			var list = '';\r\n");
      out.write("			list += '<option value=\"\" selected>선택';\r\n");
      out.write("				for(var i = 0; i < resultData.length; i++){\r\n");
      out.write("					var item = resultData[i];\r\n");
      out.write("					list += '<option value=\"'+item.mainCategory+'\">'+item.properties+'';\r\n");
      out.write("				}\r\n");
      out.write("			$('#registDetail #divisionDetail_'+num).html(list);\r\n");
      out.write("		}\r\n");
      out.write("	})\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function divisionDetailChange(num, obj){\r\n");
      out.write("	$('#registDetail #divisionSubDetail_'+num).val('');\r\n");
      out.write("	$('#registDetail #bank_'+num).val('');\r\n");
      out.write("	var data = obj;\r\n");
      out.write("	var url = '/cdCommon/selectCode'\r\n");
      out.write("	$.ajax({\r\n");
      out.write("		type : 'POST',\r\n");
      out.write("		url : url,\r\n");
      out.write("		contentType : 'application/json',\r\n");
      out.write("		data : JSON.stringify({'code' : data}),\r\n");
      out.write("		dataType : 'json',\r\n");
      out.write("		success : function(resultData){\r\n");
      out.write("			var list = '';\r\n");
      out.write("			list += '<option value=\"\" selected>선택';\r\n");
      out.write("			for(var i = 0; i < resultData.length; i++){\r\n");
      out.write("				var item = resultData[i];\r\n");
      out.write("				list += '<option value=\"'+item.mainCategory+'\">'+item.properties+'';\r\n");
      out.write("			}\r\n");
      out.write("			$('#registDetail #divisionSubDetail_'+num).html(list);\r\n");
      out.write("		}\r\n");
      out.write("	})\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function divisionSubDetailChange(num, obj){\r\n");
      out.write("	$('#registDetail #bank_'+num).val('');\r\n");
      out.write("	var data = 'BANK';\r\n");
      out.write("	var url = '/cdCommon/selectCode'\r\n");
      out.write("	$.ajax({\r\n");
      out.write("		type : 'POST',\r\n");
      out.write("		url : url,\r\n");
      out.write("		contentType : 'application/json',\r\n");
      out.write("		data : JSON.stringify({'code' : data}),\r\n");
      out.write("		dataType : 'json',\r\n");
      out.write("		success : function(resultData){\r\n");
      out.write("			var list = '';\r\n");
      out.write("			list += '<option value=\"\" selected>선택';\r\n");
      out.write("			for(var i = 0; i < resultData.length; i++){\r\n");
      out.write("				var item = resultData[i];\r\n");
      out.write("				list += '<option value=\"'+item.mainCategory+'\">'+item.properties+'';\r\n");
      out.write("			}\r\n");
      out.write("			$('#registDetail #bank_'+num).html(list);\r\n");
      out.write("		}\r\n");
      out.write("	})\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function deleteAccount(num){\r\n");
      out.write("	var div = $('#registDetail #accountDiv_'+num);\r\n");
      out.write("	div.remove();\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function regist(){\r\n");
      out.write("	console.log(\"번호확인 : \" + num);\r\n");
      out.write("	var url = '/accountBook/regist';\r\n");
      out.write("	for(var i = 0; i < num; i++){\r\n");
      out.write("		var division = $('#division_' + i).val();\r\n");
      out.write("		var divisionDetail = $('#divisionDetail_' + i).val();\r\n");
      out.write("		var divisionSubDetail = $('#divisionSubDetail_' + i).val();\r\n");
      out.write("		var bank = $('#bank_' + i).val();\r\n");
      out.write("		var date = $('#date_' + i).val();\r\n");
      out.write("		var amount = $('#amount_' + i).val();\r\n");
      out.write("		var detail = $('#detail_' + i).val();\r\n");
      out.write("		\r\n");
      out.write("		if(date == null || date == ''){\r\n");
      out.write("			continue;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		if(amount == null || amount == '' ){\r\n");
      out.write("			continue;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		if(detail == null || detail == '' ){\r\n");
      out.write("			continue;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("		$.ajax({\r\n");
      out.write("			type : 'POST',\r\n");
      out.write("			url : url,\r\n");
      out.write("			contentType : 'application/json',\r\n");
      out.write("			data : JSON.stringify({\r\n");
      out.write("					'division' : division,\r\n");
      out.write("					'divisionDetail' : divisionDetail,\r\n");
      out.write("					'divisionSubDetail' : divisionSubDetail,\r\n");
      out.write("					'bank' : bank,\r\n");
      out.write("					'date' : date,\r\n");
      out.write("					'amount' : amount,\r\n");
      out.write("					'detail' : detail\r\n");
      out.write("				}),\r\n");
      out.write("			dataType : 'json',\r\n");
      out.write("			success : function(resultData){\r\n");
      out.write("				console.log(resultData);\r\n");
      out.write("			}\r\n");
      out.write("		})\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("	\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<title>가계부 등록</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<!-- 구분및 은행 선택 -->\r\n");
      out.write("	<div>\r\n");
      out.write("		\r\n");
      out.write("		<button id=\"addrow\" name=\"addrow\" onclick=\"addrow();\">거래추가</button>\r\n");
      out.write("		<button id=\"regist\" name=\"regist\" onclick=\"regist();\">등록</button>\r\n");
      out.write("	</div>\r\n");
      out.write("	<div id=\"registDetail\">\r\n");
      out.write("			\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
